name: Release Artifacts
on:
  push:
    tags:
      - '*'
jobs:
  wheel-build:
    name: Build and Publish Release Artifacts
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.x'
      - name: Install Deps
        run: pip install -U build
      - name: Build Artifacts
        run: |
          python -m build
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/stestr*
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
